name: palm
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pyyaml
  - numpy
  - pandas
  - scipy
  - xarray
  - pytest
  - black
  - isort
  - jupyterlab
  - jupyter
  - numexpr
  - dask
  - pytorch
  - gpytorch
  - botorch
  - pip
  - pip:
    - ax-platform
    - git+https://github.com/madeline-scyphers/optiwrap.git
