name: palm_wrapper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pyyaml
  - numpy
  - pandas
  - scipy
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - pytest
  - black
  - isort
  - jupyterlab
  - jupyter
  - numexpr
  - pip
  - pip:
    - torch
    - torchaudio
    - torchvision
    - ax-platform
    - git+https://github.com/madeline-scyphers/optiwrap.git
