name: palm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pyyaml
  - numpy
  - pandas
  - scipy
  - xarray
  - pytest
  - black
  - isort
  - jupyterlab
  - jupyter
  - numexpr
  - dask
