[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 39
skip_glob = ["*env*/*", "current_version/*"]


[tool.black]
line-length = 120
preview=true
# This is a regular expression (hence the \. is escaping the ., and not a literal \.)
exclude = '''
(
    /(versioneer\.py
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | .*env.*
    | _build
    | buck-out
    | build
    | dist
    | docs/*
    )/
    | current_version/*
)
'''