optimization_options:
  input_dir: /Users/madelinescyphers/projs/palm/current_version/JOBS
  working_dir: "~/projs/palm"
  dry_run: false

model_options:

  plot_footprint: 366
  house_ratio: 0.17704884335398674
  ground_ratio: 0.508383123204112
  mean_lai: 3.1202627243474126

parameters: {}