job_name: "job1"

domain:
  x: 96  # prime factors 2,2,2,2,2,3
  x_scale: 5
  y: 216  # prime factors 2,2,2,3,3,3
  y_scale: 5
  z: 192
  z_scale: 5

plot_size:
  x: 8
  y: 8

# total_house_size: 5184  # 1 quarter of domain
house:
  domain_fraction:  4
  height: 4

trees:
  domain_fraction: 8
