 subroutine fill_canopy(zmcf,nzc,nxc,nyc,nz,NumPatchType,canpdepth ,CanopyCmdepth, DBH,Height,PatchType,TotalLAI) 

    implicit none

 ! Copyright: Gil Bohrer and Roni avissar, Duke University, 2006
  ! Input:
  ! zmcf - vector of vertical grid mesh heights in the domain into which the canopy should be extemded
  ! nxc,nyc - canopy dimensions from dims_pzRyx.txt
  ! NumPatchType - from dims_pzRyx.txt
  ! canpdepth - zRi from dims_pzRyx.txt
  ! CanopyCmdepth - length of zcm from dims_pzRyx.txt
  ! nz - length of zmcf , can be larger than nzc
  !
  ! It will read in the files generated by V-CaGe.m (except dims_pzRyx.txt that should be read earlier and its parameter values passed to this subroutine)

  ! This program assumes that Dx, Dy in the extended canopy domain are equal to Dx,Dy in the virtual canopy files
  ! It also assumes that nx=nxc, ny=nyc (but will not crash if nx<nxc and/or ny<nyc)
  
  ! Output
  ! 2-D V-CaGe Canopy arrays: DBH,Height,PatchType,TotalLAI
  ! 3-D canopy arrays:
  !            ZstemAreaU - projected stem area (on vertical plain) 
  !            ZStemAreaW - projected stem area (on horizontal plain) 
  !            CumulativeLAI -  Accumulated Leaf area / m^2 ground (from canopy top)
 
    character(200) , parameter :: CanopyInDir = '../CanopyInFiles'         !directory path to canopyIn files, generate by V-CaGe

    integer :: nzc,nxc,nyc,ng,nzcm,ncm,pt,nz,nzcc
    integer :: i,j,k,cm
    real :: kH
    real , dimension(nz) :: zmcf
    real, dimension(NumPatchType,CanopyCmdepth) :: CSProf,LAD 
    real, dimension(CanopyCmdepth) :: zcm 
    real, dimension(nxc,nyc) :: DBH,Height,TotalLAI
    integer, dimension(nxc,nyc) :: PatchType
    real, dimension(nzc,nxc,nyc) :: ZstemAreaU ,ZstemAreaW, CumulativeLAI 

    print *, 'start fill canopy'
    if (nzc.lt.canpdepth) then
       print *,'model domain too shallow- below canopy top'
    else
       nzcc = canpdepth
    endif

    nzcm = CanopyCmdepth
    ZstemAreaU=0
    ZstemAreaV=0
    ZStemAreaW=0
    CumulativeLAI=0
    CanopyOut=0
                      
    OPEN (21202,FILE=trim(CanopyInDir)//'/'//'CSProfiles.txt', STATUS='OLD') 
    OPEN (21203,FILE=trim(CanopyInDir)//'/'//'DBH.txt', STATUS='OLD') 
    OPEN (21204,FILE=trim(CanopyInDir)//'/'//'LAD.txt', STATUS='OLD') 
    OPEN (21205,FILE=trim(CanopyInDir)//'/'//'Bowen.txt', STATUS='OLD') 
    OPEN (21206,FILE=trim(CanopyInDir)//'/'//'Height.txt', STATUS='OLD') 
    OPEN (21207,FILE=trim(CanopyInDir)//'/'//'patch.txt', STATUS='OLD') 
    OPEN (21208,FILE=trim(CanopyInDir)//'/'//'TotLAI.txt', STATUS='OLD') 
    OPEN (21209,FILE=trim(CanopyInDir)//'/'//'z.txt', STATUS='OLD')
    
    do j=1,nzcm
       read (21202,*) (CSProf(i,j),i=1,NumPatchType)  
       read (21204,*) (LAD(i,j),i=1,NumPatchType)
       read (21209,*) zcm(j)
    enddo

    do j=1,nyc
       read (21203,*) (DBH(i,j),i=1,nxc)       
       read (21205,*) (Bowen(i,j),i=1,nxc)
       read (21206,*) (Height(i,j),i=1,nxc)
       read (21207,*) (PatchType(i,j),i=1,nxc) 
       read (21208,*) (TotalLAI(i,j),i=1,nxc)
    enddo

    close(21202)
    close(21203)
    close(21209)
    close(21204) 
    close(21205)
    close(21206)
    close(21207)
    close(21208)
   
    print *, 'Done reading canopy init files for grid', ng

    do i=1,nxc
       do j=1,nyc

          kH = Height(i,j)*zcm(nzcm) 
          pt = PatchType(i,j)        
          CumulativeLAI(nzcc,i,j)=0.0
          cm=nzcm
          
          do k=(nzcc),2,-1
             
             CumulativeLAI(k,i,j)=0.0
             ncm=0
             
             do while (((zcm(cm)*kH).ge.zmcf(k-1)).and.(cm.gt.1))
                ncm=ncm+1
                                     
                CumulativeLAI(k,i,j)=CumulativeLAI(k,i,j)+LAD(pt,cm)
                cm=cm-1
             enddo

             CumulativeLAI(k,i,j)=CumulativeLAI(k,i,j)* &
                  TotalLAI(i,j)+CumulativeLAI(k+1,i,j)

          enddo
       enddo
    enddo

endsubroutine

