# Single objective optimization config
optimization_options:
    objective_options:
        objectives:
            # List all of your metrics here,
            # only list 1 metric for a single objective optimization
            - boa_metric: Mean
        # List all outcome constraints here
        outcome_constraints: []
    # Here we explicitly define a generation strategy
    # for our trials.
    # This can always be done, but if left off,
    # Will be autoselected.
    # Here we say we want for first 5 trials
    # To be a random sobol survey,
    # and then the rest be Gaussian process expected improvement
    generation_strategy:
        steps:
            # Other options are possible, see Ax GenerationStrategy
            # for more information
            - model: SOBOL
              num_trials: 10
            - model: GPKG
              num_trials: -1
    # experiment options we wish to use
    # we specify an experiment name, which we can
    # also use to name our experiment running and output directory
    experiment:
        name: "palm_stuff"
    # Scheduler options we wish to use
    # Here we specify a total of 10 trials will be ran.
    scheduler:
        total_trials: 10

parameters:
    house_ratio:  # Ratio of urban area that is house (not ground, not trees)
        type: range
        bounds: [.1, .8]

    ground_ratio:  # Ratio of urban area that is ground (not house, not trees)
        type: range
        bounds: [.25, .8]

    plot_footprint:  # Size of a plot of land (area of a house and its ground it sits on)
        type: range
        bounds: [350, 950]

    mean_lai:  # The mean LAI of the canopy. There will be random perturbations to this
        type: range
        bounds: [2.0, 6.0]

parameter_constraints:
    - ground_ratio + house_ratio <= 1
    - ground_ratio + house_ratio + .6*house_ratio <= .6

model_options:
    output_start_time: 0
    output_end_time: 300
    palmrun_walltime_scalar: 3
    data_analyse_walltime_scalar: .3
    io_config: '"slurm"'
    optimization_output_dir: "~/palm/output"
    working_dir: $TMPDIR
    palm_wrapper_pkg_path:  ~/palm/palm_wrapper
    model_path: ~/palm/current_version
