# Single objective optimization config
optimization_options:
    objective_options:
        objectives:
            # List all of your metrics here,
            # only list 1 metric for a single objective optimization
            - boa_metric: Mean
        # List all outcome constraints here
        outcome_constraints: []
    # Here we explicitly define a generation strategy
    # for our trials.
    # This can always be done, but if left off,
    # Will be autoselected.
    # Here we say we want for first 5 trials
    # To be a random sobol survey,
    # and then the rest be Gaussian process expected improvement
    generation_strategy:
        steps:
            # Other options are possible, see Ax GenerationStrategy
            # for more information
            - model: SOBOL
              num_trials: 10
            - model: GPKG
              num_trials: -1
    # Scheduler options we wish to use
    # Here we specify a total of 10 trials will be ran.
    scheduler:
        total_trials: 2

parameters:
    output_start_time: 0
    output_end_time: 1200
    domain_x: 96
    domain_y: 432
    io_config: "slurm"  # '"slurm"' or '"d3#"' slurm runs in tmp directly, d3# runs in home directory and saves everything
    row_width:  # Ratio of urban area that is house (not ground, not trees)
        # type: int
        # bounds: [0, 432]
        type: fixed
        value: 0

    spacing_width:  # Ratio of urban area that is ground (not house, not trees)
        # type: int
        # bounds: [1, 432]
        type: fixed
        value: 0

    lai:  # The mean LAI of the canopy. There will be random perturbations to this
        type: range
        bounds: [2.0, 6.0]

# parameter_constraints:
#     - row_width + spacing_width <= 432

script_options:
    # run_model: sbatch slurm_launch_run_model.sh
    run_model: julia run_model.jl

model_options:
    # output_start_time: 0
    # output_end_time: 1200
    # palmrun_walltime_scalar: 3
    # data_analyse_walltime_scalar: .3
    optimization_output_dir: "~/palm/output"
    working_dir: $TMPDIR
    palm_wrapper_pkg_path:  ~/palm/palm_wrapper
    model_path: ~/palm/current_version

    domain_x: 96
    domain_y: 432
    dx: 5
    dy: 5
    dz: 5


    nodes: 1
    ntasks_per_node: 12